- name: Validate config
  shell:
    cmd: "caddy validate --config {{ caddy_conf_dir }}/{{ caddy_conf_filename }}"

- name: Restart caddy
  ansible.builtin.systemd:
    daemon_reload: true
    name: caddy
    state: restarted

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
